
SEGMENT_DETECTOR_BIRCH_THRESHOLD = 0.1
SEGMENT_DETECTOR_MIN_IN_GROUP = 5
SEGMENT_DETECTOR_MAX_GAP_IN_GROUP = 10   # microns

ARC_DETECTOR_BIRCH_THRESHOLD = 0.5
ARC_DETECTOR_MIN_IN_GROUP = 10
ARC_DETECTOR_MAX_GAP_IN_GROUP = 20       # microns
